### ISSUE TITLE
No source?

### ISSUE THREAD

**Issue by zeplar-exe** [LogicismDev/LogRPC#1]
Just found this and it's quite nice. Though, it doesn't look like the actual source code is anywhere here, and it's all packed into an executable. I believe this would be a good learning opportunity for anyone else who stumbled across this repo.

Besides, a closed source app defeats the point of GitHub in the first place.

**Comment by coffandro** [comment]
i 100% agree with this sentiment, GitHub exist primarily to share your code openly and not to just keep your guides here when you have a website you could keep it in.

**Comment by LogicismDev** [comment]
Hi there, I have posted the source code for users to modify or to examine. Feel free to examine!
