### ISSUE TITLE
Crash when opening a video in VLC

### ISSUE THREAD

**Issue by okurka12** [LogicismDev/LogRPC#4]
I have installed the latest version `1.92` and I run all default configuration. I right click in the system tray on LogRPC, click program, then go to Adobe Premiere. 

*So far works perfectly, my discord status is pretty neat showing I am currently in Premiere.*

![image](https://github.com/user-attachments/assets/4fed205a-59bb-4fdd-8f73-d882f421d21b)

But when I then open a video file in VLC Media Player by double clicking in the windows file explorer, LogRPC Shows a dialog box

> Discord must be open to use this program.

and ends immediately.

I tried launching LogRPC with admin privileges and also tried to restart discord.

Also, I am running `Windows 11 Pro version 24H2 Build 26100.1457` (It is a beta channel of the windows insider program I think). 

VLC is `3.0.21`.

Do let me know if I can do anything else to help debug this issue. I'll avoid opening video files for now 😅

**Comment by LogicismDev** [comment]
Hi there, I was able to reproduce the issue and I just released v1.93 which should fix and solve the issue with VLC Media Player. Thanks for reporting!
